Data Cleaning in Pandas

In [1]:
import pandas as pd

In [21]:
df = pd.read_excel(r"C:\Users\junai\OneDrive\Desktop\Data Analyst Store\Python\Data Cleaning in Pandas\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [11]:
#Dropping Duplicates

df.drop_duplicates()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [12]:
df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [13]:
#Dropping Columns

df.drop(columns = 'Not_Useful_Column')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [22]:
df = df.drop(columns = 'Not_Useful_Column')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [15]:
df['Last_Name'].str.lstrip("...")

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11         Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [17]:
df['Last Name'] = df['Last_Name'].str.lstrip("...")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Last Name
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,Baggins
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,Nadir
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,/White
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,Schrute
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,Snow
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,Swanson
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,Winger
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,Holmes
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,Parker
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,Gamgee
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,Potter
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,Draper
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,Knope
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,Flenderson_
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,Weasley
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,Scott
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,Kent
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,Braton
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,Skywalker

In [20]:
df["Last_Name"] = df["Last_Name"].str.lstrip("...")
df["Last_Name"] = df["Last_Name"].str.lstrip("/")
df["Last_Name"] = df["Last_Name"].str.rstrip("_")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Last Name
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,Baggins
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,Nadir
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,/White
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,Schrute
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,Snow
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,Swanson
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,Winger
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,Holmes
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,Parker
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,Gamgee
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,...Potter
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,Draper
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,Knope
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,Flenderson
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,Weasley
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,Scott
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,Kent
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,Braton
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,Skywalker

In [ ]:
#Another Way To Do This In One Go

In [23]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [24]:
df["Last_Name"].str.strip("123./")

0         Baggins
1           Nadir
2           White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11         Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
20      Skywalker
Name: Last_Name, dtype: object

In [27]:
df["Last_Name"] = df["Last_Name"].str.strip("123./_")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [32]:
df["Phone_Number"].str.replace('[^a-zA-Z0-9]',' ', regex = True)

0     123 545 5421
1     123 643 9775
2              NaN
3     123 543 2345
4     876 678 3469
5     304 762 2467
6              NaN
7     876 678 3469
8              N a
9     123 545 5421
10             NaN
11             NaN
12    123 543 2345
13    876 678 3469
14    304 762 2467
15    123 545 5421
16    123 643 9775
17             NaN
18             N a
19    876 678 3469
20    876 678 3469
Name: Phone_Number, dtype: object

In [33]:
df["Phone_Number"] = df["Phone_Number"].str.replace('[^a-zA-Z0-9]',' ', regex = True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123 545 5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123 643 9775,93 West Main Street,No,Yes
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123 543 2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876 678 3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304 762 2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876 678 3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123 545 5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123 543 2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876 678 3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304 762 2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123 545 5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123 643 9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876 678 3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876 678 3469,"910 Tatooine Road, Tatooine",Yes,N

In [36]:
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: str(x))

In [37]:
df["Phone_Number"].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])

0     123- 54-5 54
1     123- 64-3 97
2            nan--
3     123- 54-3 23
4     876- 67-8 34
5     304- 76-2 24
6            nan--
7     876- 67-8 34
8            N a--
9     123- 54-5 54
10           nan--
11           nan--
12    123- 54-3 23
13    876- 67-8 34
14    304- 76-2 24
15    123- 54-5 54
16    123- 64-3 97
17           nan--
18           N a--
19    876- 67-8 34
20    876- 67-8 34
Name: Phone_Number, dtype: object

In [38]:
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123- 54-5 54,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123- 64-3 97,93 West Main Street,No,Yes
2,1003,Walter,White,nan--,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123- 54-3 23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876- 67-8 34,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304- 76-2 24,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan--,1209 South Street,No,No
7,1008,Sherlock,Holmes,876- 67-8 34,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N a--,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123- 54-5 54,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123- 54-3 23,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876- 67-8 34,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304- 76-2 24,214 HR Avenue,N,No
15,1016,Ron,Weasley,123- 54-5 54,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123- 64-3 97,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N a--,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876- 67-8 34,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876- 67-8 34,"910 Tatooine Road, Tatooine",Yes,N

In [40]:
df["Phone_Number"] = df["Phone_Number"].str.replace('nan--', '')
df["Phone_Number"] = df["Phone_Number"].str.replace('Na--', '')
df["Phone_Number"] = df["Phone_Number"].str.replace('N a--', '')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123- 54-5 54,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123- 64-3 97,93 West Main Street,No,Yes
2,1003,Walter,White,,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123- 54-3 23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876- 67-8 34,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304- 76-2 24,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876- 67-8 34,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123- 54-5 54,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123- 54-3 23,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876- 67-8 34,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304- 76-2 24,214 HR Avenue,N,No
15,1016,Ron,Weasley,123- 54-5 54,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123- 64-3 97,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876- 67-8 34,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876- 67-8 34,"910 Tatooine Road, Tatooine",Yes,N

In [43]:
df[["Street_Address","State","Zip_Code"]] = df["Address"].str.split(pat=',', n=2, expand=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123- 54-5 54,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123- 64-3 97,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123- 54-3 23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876- 67-8 34,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304- 76-2 24,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876- 67-8 34,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123- 54-5 54,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123- 54-3 23,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876- 67-8 34,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304- 76-2 24,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123- 54-5 54,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123- 64-3 97,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876- 67-8 34,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876- 67-8 34,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [46]:
df["Paying Customer"] = df["Paying Customer"].str.replace('Yes','Y')
df["Paying Customer"] = df["Paying Customer"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123- 54-5 54,"123 Shire Lane, Shire",Y,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123- 64-3 97,93 West Main Street,N,Yes,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123- 54-3 23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876- 67-8 34,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304- 76-2 24,768 City Parkway,Y,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,N,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876- 67-8 34,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123- 54-5 54,"25th Main Street, New York",Y,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123- 54-3 23,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876- 67-8 34,343 City Parkway,Y,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304- 76-2 24,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123- 54-5 54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123- 64-3 97,"121 Paper Avenue, Pennsylvania",Y,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876- 67-8 34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876- 67-8 34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [47]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('Yes','Y')
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123- 54-5 54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123- 64-3 97,93 West Main Street,N,Y,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123- 54-3 23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876- 67-8 34,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304- 76-2 24,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876- 67-8 34,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123- 54-5 54,"25th Main Street, New York",Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123- 54-3 23,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876- 67-8 34,343 City Parkway,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304- 76-2 24,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123- 54-5 54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123- 64-3 97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876- 67-8 34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876- 67-8 34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [53]:
df = df.fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123- 54-5 54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123- 64-3 97,93 West Main Street,N,Y,93 West Main Street,,
2,1003,Walter,White,,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123- 54-3 23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876- 67-8 34,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304- 76-2 24,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876- 67-8 34,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123- 54-5 54,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123- 54-3 23,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876- 67-8 34,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304- 76-2 24,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123- 54-5 54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123- 64-3 97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,3498 Super Lane,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,,,Y,,,
19,1020,Anakin,Skywalker,876- 67-8 34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876- 67-8 34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [55]:
for x in df.index:
    if df.loc[x, "Phone_Number"] == '':
        df.drop(x, inplace=True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123- 54-5 54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123- 64-3 97,93 West Main Street,N,Y,93 West Main Street,,
3,1004,Dwight,Schrute,123- 54-3 23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876- 67-8 34,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304- 76-2 24,768 City Parkway,Y,Y,768 City Parkway,,
7,1008,Sherlock,Holmes,876- 67-8 34,98 Clue Drive,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123- 54-5 54,"25th Main Street, New York",Y,N,25th Main Street,New York,
12,1013,Don,Draper,123- 54-3 23,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876- 67-8 34,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304- 76-2 24,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123- 54-5 54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123- 64-3 97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876- 67-8 34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876- 67-8 34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [58]:
df = df.reset_index(drop=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123- 54-5 54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123- 64-3 97,93 West Main Street,N,Y,93 West Main Street,,
2,1004,Dwight,Schrute,123- 54-3 23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
3,1005,Jon,Snow,876- 67-8 34,123 Dragons Road,Y,N,123 Dragons Road,,
4,1006,Ron,Swanson,304- 76-2 24,768 City Parkway,Y,Y,768 City Parkway,,
5,1008,Sherlock,Holmes,876- 67-8 34,98 Clue Drive,N,N,98 Clue Drive,,
6,1010,Peter,Parker,123- 54-5 54,"25th Main Street, New York",Y,N,25th Main Street,New York,
7,1013,Don,Draper,123- 54-3 23,2039 Main Street,Y,N,2039 Main Street,,
8,1014,Leslie,Knope,876- 67-8 34,343 City Parkway,Y,N,343 City Parkway,,
9,1015,Toby,Flenderson,304- 76-2 24,214 HR Avenue,N,N,214 HR Avenue,,
10,1016,Ron,Weasley,123- 54-5 54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
11,1017,Michael,Scott,123- 64-3 97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
12,1020,Anakin,Skywalker,876- 67-8 34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,
13,1020,Anakin,Skywalker,876- 67-8 34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,